### ISSUE TITLE
String longer than 1500 characters

### ISSUE THREAD

**Issue by runette** [runette/ultima-ratio#94]
from the server:

Traceback (most recent call last):
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/srv/main.py", line 227, in set_entry
    gun.put()
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/simplendb/ndb.py", line 234, in put
    client.put(self)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/google/cloud/datastore/client.py", line 574, in put
    self.put_multi(entities=[entity], retry=retry, timeout=timeout)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/google/cloud/datastore/client.py", line 614, in put_multi
    current.commit(retry=retry, timeout=timeout)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/google/cloud/datastore/batch.py", line 300, in commit
    self._commit(retry=retry, timeout=timeout)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/google/cloud/datastore/batch.py", line 264, in _commit
    **kwargs,
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/google/cloud/datastore_v1/services/datastore/client.py", line 627, in commit
    response = rpc(request, retry=retry, timeout=timeout, metadata=metadata,)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/google/api_core/gapic_v1/method.py", line 145, in __call__
    return wrapped_func(*args, **kwargs)
  File "/layers/google.python.pip/pip/lib/python3.7/site-packages/google/api_core/grpc_helpers.py", line 75, in error_remapped_callable
    six.raise_from(exceptions.from_grpc_error(exc), exc)
  File "<string>", line 3, in raise_from
google.api_core.exceptions.InvalidArgument: 400 The value of property "coll_name" is longer than 1500 bytes.

**Comment by runette** [comment]
This will be fixed in the next build of V2
